STATUS_PENDING = "pending"
STATUS_APPROVED = "approved"
STATUS_IN_GARAGE = "in_garage"
STATUS_COMPLETED = "completed"
STATUS_REJECTED = "rejected"
STATUS_NO_SHOW = "no_show"

ACTIVE_SLOT_STATUSES = (STATUS_APPROVED, STATUS_IN_GARAGE)
