STATUS_PENDING = "pending"
STATUS_APPROVED = "approved"
STATUS_CHECKED_IN = "checked_in"
STATUS_COMPLETED = "completed"
STATUS_REJECTED = "rejected"

STATUS_IN_GARAGE = STATUS_CHECKED_IN  # Legacy alias

ACTIVE_SLOT_STATUSES = (STATUS_APPROVED, STATUS_CHECKED_IN)
