from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from flask import current_app
from models.db import get_db
from models.worker_model import get_worker


def generate_salary_pdf(record_id):
    buffer = BytesIO()

    # Use get_db() to respect DELETE pragma (avoids OneDrive WAL issues)
    db = get_db()
    record = db.execute("SELECT * FROM salary_records WHERE id = ?", (record_id,)).fetchone()
    
    if not record:
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        story = [Paragraph("<b>Error: Record not found</b>", getSampleStyleSheet()['Heading1'])]
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    record = dict(record)
    worker = get_worker(record['worker_id']) or {'name': 'Unknown', 'phone': ''}
    
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=colors.darkblue
    )
    
    story = [
        Paragraph("<b>SHREEJI AUTO SERVICES</b><br/><font size=12>Garage Management System</font>", title_style),
        Spacer(1, 0.5*cm),
        Paragraph(f"<b>Payslip - {record['worker_id']}</b>", styles['Heading2']),
        Spacer(1, 0.3*cm)
    ]
    
    worker_data = [
        ['Worker ID', record['worker_id']],
        ['Name', worker['name']],
        ['Phone', worker.get('phone', '')],
        ['Period', f"{record['month']}/{record['year']}"]
    ]
    worker_table = Table(worker_data)
    worker_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    story.append(worker_table)
    story.append(Spacer(1, 0.5*cm))
    
    breakdown_data = [
        ['Description', 'Amount (₹)'],
        ['Total Days', str(record['total_days'])],
        ['Attended Days', f"{record['attended_days']:.1f}"],
        ['Per Day Salary', f"{record['per_day_salary']:.2f}"],
        ['Base Salary', f"{record['base_salary']:.2f}"],
        ['Bonus', f"{record['bonus']:.2f}"],
        ['Overtime', f"{record['overtime']:.2f}"],
        ['Commission', f"{record['commission']:.2f}"],
        ['<b>Total Salary</b>', f"<b>{record['total_salary']:.2f}</b>"]
    ]
    breakdown_table = Table(breakdown_data)
    breakdown_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (1, -1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BACKGROUND', (0, -1), (-1, -1), colors.lightgreen),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
    ]))
    story.append(Paragraph("<b>Salary Breakdown:</b>", styles['Heading3']))
    story.append(breakdown_table)
    
    story.append(Spacer(1, 1*cm))
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"], alignment=TA_CENTER, fontSize=9, textColor=colors.grey)
    story.append(Paragraph("Generated by Shreeji Auto Services - Garage Management System", footer_style))
    
    doc.build(story)
    buffer.seek(0)
    return buffer


def send_salary_pdf(record_id):
    from flask import send_file
    buffer = generate_salary_pdf(record_id)
    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"salary_slip_{record_id}.pdf",
        mimetype="application/pdf"
    )
